#!/bin/bash

# Control a virtual server.
#
# @author Anders Olsson <anders@nodeone.se>


readonly VNODECTRL_VERSION="11.01-dev-alpha1"
readonly VNODECTRL_BASENAME=`basename $0`

#readonly VNODECTRL_PATH_ROOT="/Users/olsson/Workspace/devtools/vnodectrl"
readonly VNODECTRL_PATH_ROOT="/usr/vnodectrl"
readonly VNODECTRL_PATH_USER="$HOME/.vnodectrl.d"

readonly VNODECTRL_PATH_LIB="${VNODECTRL_PATH_ROOT}/lib"
readonly VNODECTRL_PATH_BIN="${VNODECTRL_PATH_ROOT}/bin"

readonly VNODECTRL_REPOSITORY_URL="https://Logaritmisk@github.com/Logaritmisk/vnodectrl.git"
readonly VNODECTRL_REPOSITORY_BRANCH="2.x-dev"


core_help() {
    cat << EOF
usage: vnodectrl [-h|--help] COMMAND


Commands:

EOF

    return 0
}


. "${VNODECTRL_PATH_LIB}/vendor/getopts_long.sh"
. "${VNODECTRL_PATH_LIB}/vendor/loader.sh"

loader_addpath "${VNODECTRL_PATH_ROOT}"

include "lib/config.sh"
include "lib/alias.sh"
include "lib/module.sh"


if [ -z "${1}" ]; then
    core_help
    
    exit 1
fi

if [ "${1:0:1}" == "@" ]; then
    alias_use "${1:1}" && shift
fi
    
case "$1" in
    -h|--help)
        core_help
        
        exit 1
    ;;
esac
    
if is_function "${1}_exec"; then
    module="${1}" && shift
        
    # dispatch 'exec_pre' "${module}" "$@"
        
    "${module}_exec" "$@"
        
    R="${?}"
        
    # dispatch 'exec_post' "${module}" "$@"
        
    exit "${R}"
fi
