#!/bin/bash
# This script let's you connect to a virtual host on amazon ec2 using the key specified by the nodes key pair

driver=$1
name=$2

ssh -i $(vnodectrl ssh-ec2-keyfile $driver $name) $(vnodectrl ssh-connection-string $driver $name)